language: generic

sudo: required

services:
 - docker

before_install:
 - docker build -t heav2n/react-test-app -f ./frontend/Dockerfile.dev ./frontend
 
script:
 - docker run -e CI=true heav2n/react-test-app npm run test
  
after_success:
 - docker build -t heav2n/docker-frontend ./frontend
 - docker build -t heav2n/docker-backend ./backend
 - docker build -t heav2n/docker-nginx ./nginx
 
 - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
 
 - docker push heav2n/docker-frontend
 - docker push heav2n/docker-backend
 - docker push heav2n/docker-nginx